# Generated by Django 3.1.5 on 2021-02-10 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ebooks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_auto_20210209_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_book', models.FileField(blank=True, null=True, upload_to=ebooks.models.ebook_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('pdf_book', models.FileField(blank=True, null=True, upload_to=ebooks.models.ebook_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('download_count', models.IntegerField(default=0, editable=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
